### ISSUE TITLE
Could you provide a sample of the training and test set?

### ISSUE THREAD

**Issue by litetoooooom** [kanishkg/stream-of-search#2]
Nice work ! Could you provide a sample of the training and test set?

**Comment by kanishkg** [comment]
Hi, yes! I'll be adding more documentation over the weekend!

**Comment by Z-MU-Z** [comment]
Hello @kanishkg, I noticed that you mentioned two weeks ago about adding more documentation over the weekend. I'm really looking forward to seeing these updates as I'm very interested in your work. If you have any new progress, could you share it? Thank you so much for your time and effort!

**Comment by kanishkg** [comment]
I have updated the readme to add documentation on how to use this repository.
