### ISSUE TITLE
Python 3.11+ not yet supported for torch.compile

### ISSUE THREAD

**Issue by Z-MU-Z** [kanishkg/stream-of-search#6]
Hello, I wonder should I  use Python 3.11?
 File "train.py", line 188, in <module>
    main(args)
  File "train.py", line 176, in main
    trainer.train()
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/transformers/trainer.py", line 1776, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/accelerate/accelerator.py", line 1228, in prepare
    result = tuple(
             ^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/accelerate/accelerator.py", line 1229, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/accelerate/accelerator.py", line 1105, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/accelerate/accelerator.py", line 1416, in prepare_model
    model = torch.compile(model, **self.state.dynamo_plugin.to_kwargs())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/torch/__init__.py", line 1441, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 413, in optimize
    check_if_dynamo_supported()
  File "/home/zmz/miniconda3/envs/sos/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 377, in check_if_dynamo_supported
    raise RuntimeError("Python 3.11+ not yet supported for torch.compile")
RuntimeError: Python 3.11+ not yet supported for torch.compile

**Comment by zijianh4** [comment]
I meet the same problem and I cannot run the train.sh when I change to Python 3.10 either.

**Comment by Z-MU-Z** [comment]
OK i will try python 3.10

**Comment by Z-MU-Z** [comment]
@zijianh4  After I use Python 3.10, I successfully run the train.sh, I use 4 gpu 4090.
Below is my debug json:
 {

            "name": "accelerate",
            "type": "python",
            "request": "launch",
            "module": "accelerate.commands.launch",
            "args": [
                "--config_file","../configs/accelerate.yaml",
                "--main_process_port","29501",
                "train.py",
                "--config",
                "../configs/sft-mix-4-cd_debug.conf",  
            ],
            "cwd": "${workspaceFolder}/src",
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": { "NCCL_P2P_DISABLE": "1",
            "NCCL_IB_DISABLE": "1",
            "PYDEVD_DISABLE_FILE_VALIDATION": "1",
            "WANDB_MODE": "dryrun",
            }
        }

**Comment by zijianh4** [comment]
> @zijianh4 After I use Python 3.10, I successfully run the train.sh, I use 4 gpu 4090. Below is my debug json: {
> 
> ```
>         "name": "accelerate",
>         "type": "python",
>         "request": "launch",
>         "module": "accelerate.commands.launch",
>         "args": [
>             "--config_file","../configs/accelerate.yaml",
>             "--main_process_port","29501",
>             "train.py",
>             "--config",
>             "../configs/sft-mix-4-cd_debug.conf",  
>         ],
>         "cwd": "${workspaceFolder}/src",
>         "console": "integratedTerminal",
>         "justMyCode": false,
>         "env": { "NCCL_P2P_DISABLE": "1",
>         "NCCL_IB_DISABLE": "1",
>         "PYDEVD_DISABLE_FILE_VALIDATION": "1",
>         "WANDB_MODE": "dryrun",
>         }
>     }
> ```

Thanks @Z-MU-Z , I find that setting NCCL_P2P_DISABLE to 1 can resolve the error on my side.

**Comment by kanishkg** [comment]
Glad y'all could figure this out, I couldn't replicate the error on my end! Closing the issue now!
