### ISSUE TITLE
About the training and test data

### ISSUE THREAD

**Issue by jiacheng-ye** [kanishkg/stream-of-search#7]
Thanks for the great work! 

My question is how to obtain the 500k SoS training data and test data used in the paper.

Are they by the following (i.e., changing 220k to 500k and removing --grow)?
```
python countdown_generate.py --seed 4 --data_dir data/b4_3_random/ --min_range 4 --start_range 4 --num_samples 500000  --offset 2
```

**Comment by Z-MU-Z** [comment]
I have the same question, i noticed that in config, there are three files, as shown below
```
  "train_file": "b4_3_random/grow2_b4_t100_n100_random.json",
  "val_file": "b4_3_random/grow2_b4_t100_n100_random.json",
  "val_target_file": "b4_3_random/grow2_b4_t100_n100_random.json",
```
How to obtain them?

**Comment by zijianh4** [comment]
I think you can refer to what I did here https://github.com/kanishkg/stream-of-search/issues/5#issuecomment-2076103613 which get these 3 files.

**Comment by kanishkg** [comment]
I just updated the gen task file!
